[package]
name = "exgui_controller_glutin"
version = "0.2.0"
authors = ["Alexander XX <freecoder.xx@gmail.com>"]
edition = "2018"

[dependencies]
exgui_core = { path = "../core" }
glutin = "0.22"
gl = "0.14"
chrono = "0.4"